name: Docker

on:
  workflow_call:

jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Docker Build
          uses: docker/setup-buildx-action@v3.10.0

        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.9
          with:
            name: programa

        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
            username: ${{ secrets.USERNAMEDOCKERHUB }}
            password: ${{ secrets.PASSWORDDOCKERHUB }}

        - name: Build and push Docker images
          uses: docker/build-push-action@v6.15.0
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: kquesso/go_ci:${{ github.run_number }}
