name: EC2

on:
  workflow_call:

jobs:
    EC2:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.9
          with:
            name: programa
            
        - name: ssh deploy
          uses: easingthemes/ssh-deploy@v2.2.11
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: /home/${{ secrets.REMOTE_USER }}/projeto-go
            EXCLUDE: “postgres-data”

        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY}}
            port: 22
            script: |
              export HOST=${{ secrets.DBHOST }}
              export USER=${{ secrets.DBUSER }}
              export PASSWORD=${{ secrets.DBPASSWORD }}
              export DBNAME=${{ secrets.DBNAME }}
              export DBPORT=${{ secrets.DBPORT }}
              export PORT=8080
              cd projeto-go
              chmod +x main
              nohup ./main &
