name: EC2

on:
  workflow_call:

jobs:
    EC2:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.9
          with:
            name: programa
            
        - name: Deploy to Staging server
          uses: easingthemes/ssh-deploy@main
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            EXCLUDE: "/dist/, /node_modules/"
