name: EC2

on:
  workflow_call:

jobs:
    EC2:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.9
          with:
            name: programa
            
        - name: ssh deploy
          uses: easingthemes/ssh-deploy@v2.2.11
          with:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            TARGET: /home/${{ secrets.REMOTE_USER }}/projeto-go
            EXCLUDE: “postgres-data”
